config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users
  resources :sessions
  resources :user_favorite_channels

  get "/tv_guide", to: "welcome#tv_guide", as: "tv_guide"
  get "/next_page", to: "welcome#next_page", as: "next_page"


  match 'auth/:provider/callback', to: 'authentications#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  validates :provider, presence: true, allow_blank: false
  validates :uid, presence: true, allow_blank: false
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications
  has_many :user_favorite_channels
  validates :email, presence: true, email: true, allow_blank: false, uniqueness: true
  validates :name, presence: true, allow_blank: false
  has_secure_password validations: false
end

app/models/user_favorite_channel.rb
class UserFavoriteChannel < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :channel_id, presence: true, uniqueness: { scope: :user_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user=(user)
    if user.present?
      @current_user = user
      session[:user_id] = user.id
    else
      @current_user = nil
      session[:user_id] = nil
    end
  end

  def get_user_faved_list
    @user_faved_list = current_user ? current_user.user_favorite_channels.pluck(:channel_id).uniq : []
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def create
    @auth = AuthHelper.new(request.env["omniauth.auth"])
    if authenticated_user?
      render nothing: true
      return
    elsif current_user
      current_user.authentications.create(authentication_params)
    else
      authenticated = Authentication.find_by(provider: @auth.provider, uid: @auth.uid)
      if authenticated
        self.current_user = authenticated.user
      else
        user = User.create(email: @auth.email, name: @auth.name)
        user.authentications.create(authentication_params)
        self.current_user = user
      end
    end
    redirect_to root_path
  end

  private

  def authentication_params
    {
      provider: @auth.provider,
      access_token: @auth.access_token,
      uid: @auth.uid,
    }
  end

  def authenticated_user?
    current_user && current_user.authentications.where(provider: @auth.provider, uid: @auth.uid).present?
  end
end

app/controllers/concerns/channel_time_event_helper.rb
module ChannelTimeEventHelper
  extend ActiveSupport::Concern

  included do
    API_TIME_FORMAT = "%Y-%m-%d %H:%M".freeze
    def period_start
      DateTime.now.in_time_zone(Time.zone).beginning_of_day.strftime(API_TIME_FORMAT)
    end

    def period_end
      (DateTime.now.in_time_zone(Time.zone) + 4.hours).strftime(API_TIME_FORMAT)
    end

    def not_current_or_future_show?(display_datetime, duration)
      current_time = DateTime.now.in_time_zone(Time.zone)
      display_datetime = ActiveSupport::TimeZone[Time.zone.name].parse(display_datetime)
      return false if display_datetime > current_time
      duration = DurationParser.new(duration)
      duration.parse
      (display_datetime + duration.hour + duration.minute + duration.second) < current_time
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
      self.current_user = user
      redirect_to root_path
    else
      flash[:notice] = "Looks like you have enter wrong email or password."
      redirect_to new_session_path
    end
  end

  def destroy
    self.current_user = nil
    redirect_to root_path
  end

  protected

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/user_favorite_channels_controller.rb
class UserFavoriteChannelsController < ApplicationController
  def create
    if current_user
      @channel_id = params[:channel_id]
      faved = current_user.user_favorite_channels.find_by(channel_id: @channel_id)
      @color = '#FFF'
      if faved
        faved.destroy
      else
        current_user.user_favorite_channels.create(channel_id: @channel_id)
        @color = '#FF0000'
      end
      respond_to do |format|
        format.js
      end
    else
      redirect_to new_session_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      self.current_user = @user
      render(js: "Turbolinks.visit('#{root_path}');")
    else
      flash[:notice] = "Looks like you have already claimed your account. Please log in to continue."
      render(js: "Turbolinks.visit('#{new_session_path}');")
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :password, :name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  PER_PAGE = 20
  include ChannelTimeEventHelper
  before_action :get_user_faved_list, only: [:index, :tv_guide]

  def index
    channels = AstroClient.get_channels(order_by: params[:order_by])
    @user_faved_list = current_user ? current_user.user_favorite_channels.pluck(:channel_id).uniq : []
    @channel_presenters = ChannelPresenter.from_list(channels)
  end

  def tv_guide
    page = params[:page].to_i
    @channel_event_groups = get_channel_event_groups(page)
  end

  def next_page
    page = params[:page].to_i
    @channel_event_groups = get_channel_event_groups(page)
    render layout: false
  end

  protected

  def get_channel_event_groups(page)
    index_start = page * PER_PAGE
    index_end = (page + 1) * PER_PAGE - 1
    index_end = index_end > channel_ids.size ? channel_ids.size : index_end
    events = AstroClient.get_events(channelId: channel_ids[index_start..index_end],
                                    periodStart: period_start,
                                    periodEnd: period_end)
    groups = events.group_by { |event| event["channelId"] }
    groups.each_value do |value|
      value.delete_if { |ch| not_current_or_future_show?(ch["displayDateTime"], ch["displayDuration"]) }
      value.sort_by! { |ch| ch["displayDateTime"] }
      value.map! { |ch| ChannelEventPresenter.new(ch) }
    end
    groups
  end

  def channel_ids
    @channel_ids ||= AstroClient.get_channel_list.map { |ch| ch["channelId"] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    "#{controller_name} #{action_name}"
  end

  def enable_turbolink
    controller_name != "users" && controller_name != "sessions"
  end
end

app/views/application/_header.html.slim
.navbar.navbar-default.navbar-fixed-top.pad-bottom-50
  .container
    ul.nav.navbar-nav.navbar-left
      li = link_to "Channel List", root_path
      li = link_to "TV Guide", tv_guide_path
    ul.nav.navbar-nav.navbar-right
      - if current_user
        li = link_to "hi #{current_user.name}", root_path
        li = link_to "Log out", session_path(1), method: :delete
      - else
        li = link_to "Sign Up", new_user_path
        li = link_to "Login", new_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
  meta name="title" content="Astro Clone"
  title Astro Clone
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  body class="#{body_class}" data-turbolinks="false"
    = render 'header'
    - [:alert, :notice].each do |type|
      = content_tag(:div, flash[type], class: "alert alert-#{type}") if flash[type].present?
    = yield

app/views/user_favorite_channels/create.js.erb
$("#fave_<%= @channel_id %>").css({fill: "<%= @color %>"})

app/views/users/new.html.slim
.signup-page
  = simple_form_for @user, remote: true,html: { class: (@user.errors.empty? ? 'signup-form-with-icon' : 'has-error') } do |form|
    = form.input :name, label: false, placeholder: 'Full Name (as per ID)', input_html: { class: "form-control" }, wrapper_html: { class: 'form-group form-group-name' }
    = form.input :email, label: false, placeholder: 'Email', input_html: { class: "form-control" }, wrapper_html: { class: 'form-group form-group-name' }
    = form.input :password, label: false, placeholder: 'Password', input_html: { class: "form-control" }, wrapper_html: { class: 'form-group form-group-password' }
    = form.submit 'Sign up', class: "btn btn-pink btn-block"

app/views/welcome/_channel_event_group.html.slim
- channel_event_groups.each do |key, events|
  .grid
    - events.each_with_index do |event, index|
      - if index.zero?
        .grid-channel
          .content
            p = event.channel_title
            p = event.channel_number
          .fave-button
            = link_to user_favorite_channels_path(channel_id: channel.channel_id), remote: true, method: :post do
              = render 'fave', channel_id: channel.channel_id
        .grid-cell
          .title = event.programme_title
          span = event.display_time
      - else
        .grid-cell
          .title = event.programme_title
          span = event.display_time

app/views/welcome/_channels.html.slim
.row
  .col-lg-12.col-md-12.nopadmobile
    ul.list-unstyled.row
      - @channel_presenters.each do |channel|
        li.col-md-4.col-sm-12.channel-each-card data-channel-name=channel.channel_title data-channel-number=channel.channel_number data-channel-id=channel.channel_id
          img.center src=channel.channel_pos_logo_small
          .card-details
            .content
              p = channel.channel_title
              p = channel.channel_number
            .fave-button
              = link_to user_favorite_channels_path(channel_id: channel.channel_id), remote: true, method: :post do
                = render 'fave', channel_id: channel.channel_id

app/views/welcome/_fave.html.erb
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="fave_<%= channel_id %>" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="32px" height="30px" viewBox="0 0 176.104 176.104" style="fill: #FFF" onmouseover="evt.target.setAttribute('opacity', '0.5')"
	 onmouseout="evt.target.setAttribute('opacity','1)');" xml:space="preserve">
<g>
	<g>
		<path stroke="red" stroke-width="9" d="M150.383,18.301c-7.13-3.928-15.308-6.187-24.033-6.187c-15.394,0-29.18,7.015-38.283,18.015
			c-9.146-11-22.919-18.015-38.334-18.015c-8.704,0-16.867,2.259-24.013,6.187C10.388,26.792,0,43.117,0,61.878
			C0,67.249,0.874,72.4,2.457,77.219c8.537,38.374,85.61,86.771,85.61,86.771s77.022-48.396,85.571-86.771
			c1.583-4.819,2.466-9.977,2.466-15.341C176.104,43.124,165.716,26.804,150.383,18.301z"/>
	</g>
</g>
</svg>

app/views/welcome/index.html.slim
#channel-container.container-fluid
  = link_to "Sort by Channel Name", root_path(order_by: "channelTitle"), id: "sort-by-channel-name"
  = link_to "Sort by Channel Number", root_path(order_by: "channelStbNumber"), id: "sort-by-channel-number"

  #channel-list data-user-faved-list=@user_faved_list
    = render 'channels'

app/views/welcome/index.js.erb
$('#channel-list').html("<%= j render(:partial => 'channels') %>");

app/views/welcome/next_page.html.slim
= render "channel_event_group", channel_event_groups: @channel_event_groups

app/views/welcome/tv_guide.html.slim
#channel-list data-user-faved-list=@user_faved_list
.section
  .load-more-container data-page=0
    = render "channel_event_group", channel_event_groups: @channel_event_groups

.section.section-loading
  img src="#{asset_path('ring.svg')}"
  span.meta = "Loading more..."